### ISSUE TITLE
In README.md link missing

### ISSUE THREAD

**Issue by aSquare14** [maxroberts/Keithley-2400-SourceMeter-Python-Interface#1]
In the Notes section , the link is missing. Can you please update that ?

**Comment by maxroberts** [comment]
Hmm... whatever link I was talking about there is definitely outdated now. Maybe try this: https://stackoverflow.com/questions/39821177/python-pyqt-on-macos-sierra

This repo is probably only useful for the interface to the Keithley device. There are better ways to visualize the data.

**Comment by aSquare14** [comment]
Okay ! Thanks Max :+1:
