### ISSUE TITLE
global name 'Example' is not defined

### ISSUE THREAD

**Issue by Rromotpd** [maxroberts/Keithley-2400-SourceMeter-Python-Interface#4]
Hello. I'd like to use this GUI with my Keithley 2400. When I want to run command from readme (python keithley_gui.py port_for_keithley) it returns :
 
  File "keithley_gui.py", line 24, in __init__
    super(Example, self).__init__()
NameError: global name 'Example' is not defined

I'm using USB-RS232 cable and I can connect with device when I use open_resource from VISA.

**Comment by maxroberts** [comment]
Yup, definitely a typo from before. Corrected in f58d4c0. Thanks!
